#!/usr/bin/env python3
"""Export the project skills + ops CLI as a sanitized, shareable bundle.

Copies `.claude/skills/**` and `scripts/ops/pbtb_ops.py` into OUT_DIR with every
deployment-specific identifier replaced by an angle-bracket placeholder, writes a
README explaining the placeholders, then refuses to finish if any identifier is
still present. Re-run it whenever the skills change; the bundle is what gets
published (e.g. to a separate public repo), never the raw skills.

    python scripts/ops/export_skills.py OUT_DIR [--owner OWNER] [--repo REPO]

The replacement map is the single place to extend when a new identifier appears
in a skill. Longer strings are replaced first so `owner/repo` becomes one
placeholder rather than two partial ones.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# Concrete values live only here and in the repo; the bundle sees placeholders.
IDENTIFIERS = [
    ("iengai.github.io/pbtb-rust", "<OWNER>.github.io/<REPO>"),
    ("iengai/pbtb-rust", "<OWNER>/<REPO>"),
    ("025418542265", "<AWS_ACCOUNT_ID>"),
    ("scalable-cluster-dev", "<PROJECT>-<ENV>"),
    ("scalable-cluster", "<PROJECT>"),
    ("ap-northeast-1", "<REGION>"),
    ("iengai", "<DEPLOY_ACCOUNT>"),
    ("nat-instance", "<NAT_INSTANCE_TAG>"),
    ("E:/projects/passivbot", "<PASSIVBOT_SRC_DIR>"),
]
# Anything matching these must never reach the bundle, even if not in the map.
FORBIDDEN = [
    r"\b\d{12}\b",             # any AWS account id
    r"\bi-[0-9a-f]{17}\b",     # EC2 instance ids
    r"\b\d{9,10}\b",           # Telegram user ids / bot ids
    r"kk-xaiondata", r"iengai",
    r"arn:aws:[a-z0-9-]+:[a-z0-9-]+:\d{12}",
]
ALLOWED_NUMERIC = {"20250419", "2012-10-17"}  # dates that look like ids

README = """# pbtb Claude skills (sanitized export)

Project skills and a read-only ops CLI for running a small AWS trading-bot
deployment (Telegram control bot on an EC2 host, one ECS task per bot, a restart
lambda, a collector lambda, a static site) with Claude Code. Extracted from a
live setup and sanitized: every account, region, project and host identifier is
an angle-bracket placeholder.

| Placeholder | Meaning |
|---|---|
| `<OWNER>/<REPO>` | the GitHub repository the skills live in |
| `<DEPLOY_ACCOUNT>` | the gh account with push rights and `workflow` scope |
| `<AWS_ACCOUNT_ID>`, `<REGION>` | AWS account / region |
| `<PROJECT>`, `<ENV>` | resource-name prefix, e.g. `myproj` + `dev` -> `myproj-dev-cluster` |
| `<NAT_INSTANCE_TAG>` | `Name` tag of the EC2 host that runs the Telegram bot |
| `<PASSIVBOT_SRC_DIR>` | local checkout of the trading-engine source used for image builds |

## Layout

```
.claude/skills/
  pbtb-triage/   debugging loop, symptom router, component map, playbooks
  verify/        the verification gate (scripts/gate.sh)
  pbtb-deploy/   rollout order and coupling rules
  pbtb-ship/     branch / rebase / PR / merge mechanics
scripts/ops/pbtb_ops.py   bot-status, deploy-audit, telebot-logs, lambda-logs, codebuild-log, smoke-lambda
```

## Adapting it

1. Copy `.claude/skills/` and `scripts/ops/pbtb_ops.py` into your repo.
2. Replace the placeholders in the skill files (`grep -rn '<[A-Z_]*>' .claude/skills`).
3. The CLI needs no edits: set `PBTB_PROJECT`, `PBTB_ENV`, `PBTB_REGION`,
   `PBTB_AWS_PROFILE`, `PBTB_NAT_TAG`, `PBTB_PASSIVBOT_ECR_REPO` (its defaults are
   the placeholders and fail loudly).
4. Read `pbtb-triage/references/component-map.md` first and rewrite any row that
   does not match your topology; the *shape* of the table is the reusable part.

The tooling quirks section (Windows Git Bash path mangling, `set -e` not stopping
multi-step commands in the Claude Code Bash tool, the AWS CLI dying on a cp932
console) is host-specific but cheap to keep.

Generated by `scripts/ops/export_skills.py` from the source repository.
"""


def sanitize(text: str) -> str:
    for old, new in IDENTIFIERS:
        text = text.replace(old, new)
    return text


def check(path: Path, text: str) -> list[str]:
    bad = []
    for pat in FORBIDDEN:
        for m in re.finditer(pat, text):
            tok = m.group(0)
            if tok in ALLOWED_NUMERIC:
                continue
            line = text.count("\n", 0, m.start()) + 1
            bad.append(f"{path}:{line}: {tok}")
    return bad


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("out_dir")
    a = ap.parse_args()
    out = Path(a.out_dir).resolve()
    if out.exists():
        shutil.rmtree(out)
    (out / ".claude").mkdir(parents=True)
    (out / "scripts" / "ops").mkdir(parents=True)

    sources = list((ROOT / ".claude" / "skills").rglob("*"))
    sources.append(ROOT / "scripts" / "ops" / "pbtb_ops.py")
    problems, written = [], 0
    for src in sources:
        if src.is_dir():
            continue
        rel = src.relative_to(ROOT)
        dst = out / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        text = sanitize(src.read_text(encoding="utf-8"))
        problems += check(rel, text)
        dst.write_text(text, encoding="utf-8", newline="\n")
        if src.suffix == ".sh":
            os.chmod(dst, 0o755)
        written += 1
    (out / "README.md").write_text(README, encoding="utf-8", newline="\n")

    # The exported CLI must still be valid Python and parse its own arguments.
    r = subprocess.run([sys.executable, str(out / "scripts" / "ops" / "pbtb_ops.py"), "--help"],
                       capture_output=True, text=True)
    if r.returncode != 0:
        problems.append(f"exported pbtb_ops.py --help failed: {r.stderr.strip()[-300:]}")

    print(f"exported {written} files to {out}")
    if problems:
        print("REFUSING: identifiers or breakage remain:", file=sys.stderr)
        for p in problems:
            print("  -", p, file=sys.stderr)
        return 1
    print("sanitization check: clean")
    return 0


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    raise SystemExit(main())
